### ISSUE TITLE
Unknown event type value 4

### ISSUE THREAD

**Issue by Eddio0141** [Eddio0141/osu-file-parser#2]
[https://osu.ppy.sh/beatmapsets/4651](https://osu.ppy.sh/beatmapsets/4651) `Nico Nico Douga - BARUSA of MIKOSU (DJPop).osb` - line 7
This contains the event type value 4 with the full line being `4,3,1,"black.png",320,240`

My guess is that it has similar purpose as `Background` but I really don't know the actual purpose of this

Need somebody that has knowledge on this to give me information

**Comment by Eddio0141** [comment]
yeah it's something very old
I was trying to come up with some name for the event type and the field names
There seems to be few unnamed event types that are just numbers

**Comment by zihadmahiuddin** [comment]
> yeah it's something very old I was trying to come up with some name for the event type and the field names There seems to be few unnamed event types that are just numbers

Oops, my bad. I was looking at the beatmap decoder.
There's a separate [decoder for storyboards](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs#L117), which does handle the `Sprite` event type as well. And it seems the fields are `layer`, `origin`, `path`, `x`, and `y` though I'm not sure what `layer` and `origin` are or how they're used.

**Comment by zihadmahiuddin** [comment]
Looks like there is a screenshot of examples using the `Sprite` event, `Background` layer, and `Centre` origin [on the wiki](https://osu.ppy.sh/wiki/en/Storyboard/Scripting)
I also found the enum types for the [layer](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/Legacy/LegacyStoryLayer.cs) and [origin](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/Legacy/LegacyOrigins.cs) fields.
I think these will be enough to implement the structure for this event type (and the others if missing).

**Comment by Eddio0141** [comment]
Thank you this seems like it
